collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.5752688
color:
  saturation: 0.8637993
  lightness: 1
  brandStrength: 0.5698925
  brandColors:
    - '#FFF3FE'
    - '#FF01FF'
    - '#FFBDFF'
    - '#D880D7'
    - '#D139D0'
  rhythmicContrast: 0.4802867
layout_spectrum: 0.281362
name: OPERAPOLIS
